function mappedFile = readOCTmapFile(varargin)
% Maps a .dat file into memory
% SYNTAX:
% 
% INPUTS:
% 
% OUTPUTS:
% 
%_______________________________________________________________________________
% Copyright (C) 2011 LIOM Laboratoire d'Imagerie Optique et Moléculaire
%                    École Polytechnique de Montréal
% Edgar Guevara
% 2011/09/20

% only want 1 optional inputs at most
numVarArgs = length(varargin);
if numVarArgs > 1
    error('readOCTmapFile:TooManyInputs', ...
        'requires at most 1 optional input');
end

% set defaults for optional inputs (false)
optArgs = {false};

% now put these defaults into the optArgs cell array, 
% and overwrite the ones specified in varargin.
optArgs(1:numVarArgs) = varargin;
% or ...
% [optargs{1:numvarargs}] = varargin{:};

% Place optional args in memorable variable names
[chooseFile] = optArgs{:};

% Load default parameters
ss_oct_get_defaults

% Modifies values of global variable
global SSOctDefaults
% Read acquisition parameters generated by LabView
SSOctDefaults.acqParam = readCSVfile(fullfile(SSOctDefaults.dirExp,...
    SSOctDefaults.acqParamFileName));
if chooseFile
    % If we decide to choose a file
    [fileName, pathName] = uigetfile('*.dat', 'Pick an M-file');
    if isequal(fileName,0) || isequal(pathName,0)
        % Return an empty matrix
        mappedFile = [];
        disp('User pressed cancel')
        return
    else
        % Read acquisition parameters generated by LabView
        SSOctDefaults.acqParam = readCSVfile(fullfile(SSOctDefaults.dirExp,...
            SSOctDefaults.acqParamFileName));
    end
else
    % Load most recent experiment
    cd(SSOctDefaults.dirCurrExp)
    mappedFile = memmapfile(SSOctDefaults.CurrExpFileName, 'format', 'int16',...
        'writable', false);
    mappedFile.Format = {'int16' [SSOctDefaults.NSAMPLES SSOctDefaults.nLinesPerFrame...
        SSOctDefaults.nFrames] 'rawData'};
end

% ==============================================================================
% [EOF]
