// Generated by FFT 2.1.3 [Altera, IP Toolbench v1.2.7 build38]
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2005 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.

	fft_small	fft_small_inst(
		.clk(clk_sig),
		.reset(reset_sig),
		.master_sink_dav(master_sink_dav_sig),
		.master_sink_sop(master_sink_sop_sig),
		.master_source_dav(master_source_dav_sig),
		.inv_i(inv_i_sig),
		.data_real_in(data_real_in_sig),
		.data_imag_in(data_imag_in_sig),
		.fft_real_out(fft_real_out_sig),
		.fft_imag_out(fft_imag_out_sig),
		.exponent_out(exponent_out_sig),
		.master_sink_ena(master_sink_ena_sig),
		.master_source_sop(master_source_sop_sig),
		.master_source_eop(master_source_eop_sig),
		.master_source_ena(master_source_ena_sig));
