// megafunction wizard: %FFT v2.1.3%
// GENERATION: XML

// ============================================================
// Megafunction Name(s):
// 			asj_fft_dualstream
// ============================================================
// Generated by FFT 2.1.3 [Altera, IP Toolbench v1.2.7 build38]
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2005 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.


module fft_small (
	clk,
	reset,
	master_sink_dav,
	master_sink_sop,
	master_source_dav,
	inv_i,
	data_real_in,
	data_imag_in,
	fft_real_out,
	fft_imag_out,
	exponent_out,
	master_sink_ena,
	master_source_sop,
	master_source_eop,
	master_source_ena);


	input		clk;
	input		reset;
	input		master_sink_dav;
	input		master_sink_sop;
	input		master_source_dav;
	input		inv_i;
	input	[15:0]	data_real_in;
	input	[15:0]	data_imag_in;
	output	[15:0]	fft_real_out;
	output	[15:0]	fft_imag_out;
	output	[5:0]	exponent_out;
	output		master_sink_ena;
	output		master_source_sop;
	output		master_source_eop;
	output		master_source_ena;


	asj_fft_dualstream	asj_fft_dualstream_inst(
		.clk(clk),
		.reset(reset),
		.master_sink_dav(master_sink_dav),
		.master_sink_sop(master_sink_sop),
		.master_source_dav(master_source_dav),
		.inv_i(inv_i),
		.data_real_in(data_real_in),
		.data_imag_in(data_imag_in),
		.fft_real_out(fft_real_out),
		.fft_imag_out(fft_imag_out),
		.exponent_out(exponent_out),
		.master_sink_ena(master_sink_ena),
		.master_source_sop(master_source_sop),
		.master_source_eop(master_source_eop),
		.master_source_ena(master_source_ena));

	defparam
		asj_fft_dualstream_inst.nps = 16384,
		asj_fft_dualstream_inst.bfp = 1,
		asj_fft_dualstream_inst.nume = 2,
		asj_fft_dualstream_inst.mpr = 16,
		asj_fft_dualstream_inst.twr = 16,
		asj_fft_dualstream_inst.bpr = 16,
		asj_fft_dualstream_inst.bpb = 4,
		asj_fft_dualstream_inst.fpr = 4,
		asj_fft_dualstream_inst.mram = 1,
		asj_fft_dualstream_inst.m512 = 0,
		asj_fft_dualstream_inst.mult_type = 0,
		asj_fft_dualstream_inst.mult_imp = 0,
		asj_fft_dualstream_inst.srr = "AUTO_SHIFT_REGISTER_RECOGNITION=OFF",
		asj_fft_dualstream_inst.rfs1 = "fft_small_1n16384sin.hex",
		asj_fft_dualstream_inst.rfs2 = "fft_small_2n16384sin.hex",
		asj_fft_dualstream_inst.rfs3 = "fft_small_3n16384sin.hex",
		asj_fft_dualstream_inst.rfc1 = "fft_small_1n16384cos.hex",
		asj_fft_dualstream_inst.rfc2 = "fft_small_2n16384cos.hex",
		asj_fft_dualstream_inst.rfc3 = "fft_small_3n16384cos.hex";
endmodule

// =========================================================
// FFT Wizard Data
// ===============================
// DO NOT EDIT FOLLOWING DATA
// @Altera, IP Toolbench@
// Warning: If you modify this section, FFT Wizard may not be able to reproduce your chosen configuration.
// 
// Retrieval info: <?xml version="1.0"?>
// Retrieval info: <MEGACORE title="FFT MegaCore Function"  version="2.1.3"  iptb_version="v1.2.7 build38"  format_version="120" >
// Retrieval info:  <NETLIST_SECTION class="altera.ipbu.flowbase.netlist.model.FFTModelClass"  active_core="asj_fft_dualstream" >
// Retrieval info:   <STATIC_SECTION>
// Retrieval info:    <PRIVATES>
// Retrieval info:     <NAMESPACE name = "parameterization">
// Retrieval info:      <PRIVATE name = "DEVICE" value="Stratix II"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "NPS" value="16384"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "MPR" value="16"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "TWR" value="16"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "ARCH" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "NUME" value="2"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "ENGINE_THROUGHPUT" value="4"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "BFP" value="1"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "MULT_TYPE" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "MULT_IMP" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "MEGA" value="1"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "M512" value="1"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "LOGIC_IN_RAM" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "NUM_LE" value="7494"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "NUM_M4K" value="330"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "NUM_MEGA" value="2"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "NUM_M512" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "NUM_DSP" value="36"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "NUM_CALC_CYCLES" value="16384"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "NUM_BLK_THROUGHPUT_CYCLES" value="16384"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "rfs1" value="romfile_1024.hex"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "rfs2" value="romfile_1024.hex"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "rfs3" value="romfile_1024.hex"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "rfc1" value="romfile_1024.hex"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "rfc2" value="romfile_1024.hex"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "rfc3" value="romfile_1024.hex"  type="STRING"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "symbol"/>
// Retrieval info:     <NAMESPACE name = "simgen_enable">
// Retrieval info:      <PRIVATE name = "language" value="Verilog HDL"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "enabled" value="1"  type="BOOLEAN"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "quartus_settings">
// Retrieval info:      <PRIVATE name = "DEVICE" value="AUTO"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "FAMILY" value="Stratix II"  type="STRING"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "serializer"/>
// Retrieval info:    </PRIVATES>
// Retrieval info:    <FILES/>
// Retrieval info:    <CONSTANTS>
// Retrieval info:     <CONSTANT name = "nps" value="16384"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "bfp" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "nume" value="2"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "mpr" value="16"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "twr" value="16"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "bpr" value="16"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "bpb" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "fpr" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "mram" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "m512" value="0"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "mult_type" value="0"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "mult_imp" value="0"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "srr" value="AUTO_SHIFT_REGISTER_RECOGNITION=OFF"  type="STRING" />
// Retrieval info:     <CONSTANT name = "rfs1" value="fft_small_1n16384sin.hex"  type="STRING" />
// Retrieval info:     <CONSTANT name = "rfs2" value="fft_small_2n16384sin.hex"  type="STRING" />
// Retrieval info:     <CONSTANT name = "rfs3" value="fft_small_3n16384sin.hex"  type="STRING" />
// Retrieval info:     <CONSTANT name = "rfc1" value="fft_small_1n16384cos.hex"  type="STRING" />
// Retrieval info:     <CONSTANT name = "rfc2" value="fft_small_2n16384cos.hex"  type="STRING" />
// Retrieval info:     <CONSTANT name = "rfc3" value="fft_small_3n16384cos.hex"  type="STRING" />
// Retrieval info:    </CONSTANTS>
// Retrieval info:    <PORTS>
// Retrieval info:     <PORT name = "clk" direction="INPUT"  connect_to="clk"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "reset" direction="INPUT"  connect_to="reset"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "master_sink_dav" direction="INPUT"  connect_to="master_sink_dav"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "master_sink_sop" direction="INPUT"  connect_to="master_sink_sop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "master_source_dav" direction="INPUT"  connect_to="master_source_dav"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "inv_i" direction="INPUT"  connect_to="inv_i"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_real_in" direction="INPUT"  connect_to="data_real_in"  default="NODEFVAL"  width="16"  description="" />
// Retrieval info:     <PORT name = "data_imag_in" direction="INPUT"  connect_to="data_imag_in"  default="NODEFVAL"  width="16"  description="" />
// Retrieval info:     <PORT name = "fft_real_out" direction="OUTPUT"  connect_to="fft_real_out"  default="NODEFVAL"  width="16"  description="" />
// Retrieval info:     <PORT name = "fft_imag_out" direction="OUTPUT"  connect_to="fft_imag_out"  default="NODEFVAL"  width="16"  description="" />
// Retrieval info:     <PORT name = "exponent_out" direction="OUTPUT"  connect_to="exponent_out"  default="NODEFVAL"  width="6"  description="" />
// Retrieval info:     <PORT name = "master_sink_ena" direction="OUTPUT"  connect_to="master_sink_ena"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "master_source_sop" direction="OUTPUT"  connect_to="master_source_sop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "master_source_eop" direction="OUTPUT"  connect_to="master_source_eop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "master_source_ena" direction="OUTPUT"  connect_to="master_source_ena"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:    </PORTS>
// Retrieval info:    <LIBRARIES>
// Retrieval info:     <LIBRARY name = "fft_lib" fft_pack="" />
// Retrieval info:    </LIBRARIES>
// Retrieval info:   </STATIC_SECTION>
// Retrieval info:  </NETLIST_SECTION>
// Retrieval info: </MEGACORE>
// =========================================================
