// ============================================================================
//  This code is generated by Terasic System Builder
// ============================================================================

module DE4_DDR2(

	//////// CLOCK //////////
	GCLKIN,
	GCLKOUT_FPGA,
	MAX_CONF_D,
	MAX_PLL_D,
	OSC_50_Bank2,
	OSC_50_Bank3,
	OSC_50_Bank4,
	OSC_50_Bank5,
	OSC_50_Bank6,
	OSC_50_Bank7,
	PLL_CLKIN_p,

	//////// LED x 8 //////////
	LED,

	//////// BUTTON x 4 //////////
	BUTTON,
	CPU_RESET_n,
	EXT_IO,

	//////// DDR2 SODIMM //////////
	M1_DDR2_addr,
	M1_DDR2_ba,
	M1_DDR2_cas_n,
	M1_DDR2_cke,
	M1_DDR2_clk,
	M1_DDR2_clk_n,
	M1_DDR2_cs_n,
	M1_DDR2_dm,
	M1_DDR2_dq,
	M1_DDR2_dqs,
	M1_DDR2_dqsn,
	M1_DDR2_odt,
	M1_DDR2_ras_n,
	M1_DDR2_SA,
	M1_DDR2_SCL,
	M1_DDR2_SDA,
	M1_DDR2_we_n

);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input		          		GCLKIN;
output		          		GCLKOUT_FPGA;
inout		     [2:0]		MAX_CONF_D;
output		     [2:0]		MAX_PLL_D;
input		          		OSC_50_Bank2;
input		          		OSC_50_Bank3;
input		          		OSC_50_Bank4;
input		          		OSC_50_Bank5;
input		          		OSC_50_Bank6;
input		          		OSC_50_Bank7;
input		          		PLL_CLKIN_p;

//////////// LED x 8 //////////
output		     [7:0]		LED;

//////////// BUTTON x 4 //////////
input		     [3:0]		BUTTON;
input		          		CPU_RESET_n;
inout		          		EXT_IO;

//////////// DDR2 SODIMM //////////
output		    [15:0]		M1_DDR2_addr;
output		     [2:0]		M1_DDR2_ba;
output		          		M1_DDR2_cas_n;
output		     [1:0]		M1_DDR2_cke;
inout		     [1:0]		M1_DDR2_clk;
inout		     [1:0]		M1_DDR2_clk_n;
output		     [1:0]		M1_DDR2_cs_n;
output		     [7:0]		M1_DDR2_dm;
inout		    [63:0]		M1_DDR2_dq;
inout		     [7:0]		M1_DDR2_dqs;
inout		     [7:0]		M1_DDR2_dqsn;
output		     [1:0]		M1_DDR2_odt;
output		          		M1_DDR2_ras_n;
output		     [1:0]		M1_DDR2_SA;
output		          		M1_DDR2_SCL;
inout		          		M1_DDR2_SDA;
output		          		M1_DDR2_we_n;


//=======================================================
//  REG/WIRE declarations
//=======================================================
wire 						rstn;
wire						clk50MHz;

//=======================================================
//  Structural coding
//=======================================================

assign 	rstn 				= CPU_RESET_n;
assign	clk50MHz			= OSC_50_Bank3;

system system_inst
(
	// global signals:
	.clock_master(clk50MHz), 								// input
	.reset_n(rstn) ,										// input

	// the ddr2
	.ddr2_aux_full_rate_clk_out() ,							// output
	.ddr2_aux_half_rate_clk_out() ,							// output
	.ddr2_phy_clk_out() ,									// output
	
	.aux_scan_clk_from_the_ddr2() ,							// output
	.aux_scan_clk_reset_n_from_the_ddr2() ,					// output
	.dll_reference_clk_from_the_ddr2() ,					// output
	.dqs_delay_ctrl_export_from_the_ddr2() ,				// output [5:0]
	
	.global_reset_n_to_the_ddr2(rstn) ,						// input
	
	.local_init_done_from_the_ddr2() ,						// output
	.local_refresh_ack_from_the_ddr2() ,					// output
	.local_wdata_req_from_the_ddr2() ,						// output
	
	.mem_addr_from_the_ddr2(M1_DDR2_addr) ,					// output [13:0]
	.mem_ba_from_the_ddr2(M1_DDR2_ba) ,						// output [2:0]
	.mem_cas_n_from_the_ddr2(M1_DDR2_cas_n) ,				// output
	.mem_cke_from_the_ddr2(M1_DDR2_cke) ,					// output
	.mem_clk_n_to_and_from_the_ddr2(M1_DDR2_clk_n) ,		// inout [1:0]
	.mem_clk_to_and_from_the_ddr2(M1_DDR2_clk) ,			// inout [1:0]
	.mem_cs_n_from_the_ddr2(M1_DDR2_cs_n) ,					// output
	.mem_dm_from_the_ddr2(M1_DDR2_dm) ,						// output [7:0]
	.mem_dq_to_and_from_the_ddr2(M1_DDR2_dq) ,				// inout [63:0]
	.mem_dqs_to_and_from_the_ddr2(M1_DDR2_dqs) ,			// inout [7:0]
	.mem_dqsn_to_and_from_the_ddr2(M1_DDR2_dqsn) ,			// inout [7:0]
	.mem_odt_from_the_ddr2(M1_DDR2_odt) ,					// output
	.mem_ras_n_from_the_ddr2(M1_DDR2_ras_n) ,				// output
	.mem_we_n_from_the_ddr2(M1_DDR2_we_n) ,					// output
	
	.oct_ctl_rs_value_to_the_ddr2() ,						// input [13:0]
	.oct_ctl_rt_value_to_the_ddr2() ,						// input [13:0]
	.reset_phy_clk_n_from_the_ddr2() ,						// output

	// ddr2 psd i2c WHERE DO I CONNECT THEM???????
//	.out_port_from_the_ddr2_i2c_scl(M1_DDR2_SCL),
//	.out_port_from_the_ddr2_i2c_sa(M1_DDR2_SA),
//	.bidir_port_to_and_from_the_ddr2_i2c_sda(M1_DDR2_SDA),
	
	// the Master Read
	.control_done_from_the_master_read() ,	// output
	.control_early_done_from_the_master_read() ,	// output
	.control_fixed_location_to_the_master_read() ,	// input
	.control_go_to_the_master_read() ,	// input
	.control_read_base_to_the_master_read() ,	// input [29:0]
	.control_read_length_to_the_master_read() ,	// input [29:0]
	.user_buffer_output_data_from_the_master_read() ,	// output [31:0]
	.user_data_available_from_the_master_read() ,	// output
	.user_read_buffer_to_the_master_read() ,	// input
	
	// the Master Write
	.control_done_from_the_master_write() ,	// output
	.control_fixed_location_to_the_master_write() ,	// input
	.control_go_to_the_master_write() ,	// input
	.control_write_base_to_the_master_write() ,	// input [29:0]
	.control_write_length_to_the_master_write() ,	// input [29:0]
	.user_buffer_full_from_the_master_write() ,	// output
	.user_buffer_input_data_to_the_master_write() ,	// input [31:0]
	.user_write_buffer_to_the_master_write() 	// input
);

TestWrite TestWrite_inst
(
	.RSTn(rstn) ,	// input  RSTn_sig
	.CLK48MHZ(clk50MHz) ,	// input  CLK48MHZ_sig
	.control_go() ,	// output  control_go_sig
	.control_write_base() ,	// output [23:0] control_write_base_sig
	.control_write_length() ,	// output [23:0] control_write_length_sig
	.control_done() ,	// input  control_done_sig
	.user_buffer_data() ,	// output [31:0] user_buffer_data_sig
	.user_buffer_full() ,	// input  user_buffer_full_sig
	.user_write_buffer() ,	// output  user_write_buffer_sig
	.addressLastCompleteWrite() ,	// output [23:0] addressLastCompleteWrite_sig
	.addressLastCompleteRead() ,	// input [23:0] addressLastCompleteRead_sig
	.writingDone() ,	// output  writingDone_sig
	.debugOut() ,	// output [31:0] debugOut_sig
	.errorFull() 	// output  errorFull_sig
);

TestRead TestRead_inst
(
	.RSTn(rstn) ,	// input  RSTn_sig
	.CLK48MHZ(clk50MHz) ,	// input  CLK48MHZ_sig
	.control_go() ,	// output  control_go_sig
	.control_read_base() ,	// output [23:0] control_read_base_sig
	.control_read_length() ,	// output [23:0] control_read_length_sig
	.control_done() ,	// input  control_done_sig
	.user_buffer_data() ,	// input [31:0] user_buffer_data_sig
	.user_read_buffer() ,	// output  user_read_buffer_sig
	.user_data_available() ,	// input  user_data_available_sig
	.addressLastCompleteWrite() ,	// input [23:0] addressLastCompleteWrite_sig
	.addressLastCompleteRead() ,	// output [23:0] addressLastCompleteRead_sig
	.readingDone() ,	// output  readingDone_sig
	.debugOut() ,	// output [31:0] debugOut_sig
	.errorData() 	// output [2:0] errorData_sig
);

endmodule
