  //Example instantiation for system 'DE4_SOPC'
  DE4_SOPC DE4_SOPC_inst
    (
      .aux_scan_clk_from_the_ddr2              (aux_scan_clk_from_the_ddr2),
      .aux_scan_clk_reset_n_from_the_ddr2      (aux_scan_clk_reset_n_from_the_ddr2),
      .bidir_port_to_and_from_the_ddr2_i2c_sda (bidir_port_to_and_from_the_ddr2_i2c_sda),
      .clk_50                                  (clk_50),
      .ddr2_aux_full_rate_clk_out              (ddr2_aux_full_rate_clk_out),
      .ddr2_aux_half_rate_clk_out              (ddr2_aux_half_rate_clk_out),
      .ddr2_phy_clk_out                        (ddr2_phy_clk_out),
      .dll_reference_clk_from_the_ddr2         (dll_reference_clk_from_the_ddr2),
      .dqs_delay_ctrl_export_from_the_ddr2     (dqs_delay_ctrl_export_from_the_ddr2),
      .global_reset_n_to_the_ddr2              (global_reset_n_to_the_ddr2),
      .in_port_to_the_button                   (in_port_to_the_button),
      .local_init_done_from_the_ddr2           (local_init_done_from_the_ddr2),
      .local_refresh_ack_from_the_ddr2         (local_refresh_ack_from_the_ddr2),
      .local_wdata_req_from_the_ddr2           (local_wdata_req_from_the_ddr2),
      .mem_addr_from_the_ddr2                  (mem_addr_from_the_ddr2),
      .mem_ba_from_the_ddr2                    (mem_ba_from_the_ddr2),
      .mem_cas_n_from_the_ddr2                 (mem_cas_n_from_the_ddr2),
      .mem_cke_from_the_ddr2                   (mem_cke_from_the_ddr2),
      .mem_clk_n_to_and_from_the_ddr2          (mem_clk_n_to_and_from_the_ddr2),
      .mem_clk_to_and_from_the_ddr2            (mem_clk_to_and_from_the_ddr2),
      .mem_cs_n_from_the_ddr2                  (mem_cs_n_from_the_ddr2),
      .mem_dm_from_the_ddr2                    (mem_dm_from_the_ddr2),
      .mem_dq_to_and_from_the_ddr2             (mem_dq_to_and_from_the_ddr2),
      .mem_dqs_to_and_from_the_ddr2            (mem_dqs_to_and_from_the_ddr2),
      .mem_dqsn_to_and_from_the_ddr2           (mem_dqsn_to_and_from_the_ddr2),
      .mem_odt_from_the_ddr2                   (mem_odt_from_the_ddr2),
      .mem_ras_n_from_the_ddr2                 (mem_ras_n_from_the_ddr2),
      .mem_we_n_from_the_ddr2                  (mem_we_n_from_the_ddr2),
      .oct_ctl_rs_value_to_the_ddr2            (oct_ctl_rs_value_to_the_ddr2),
      .oct_ctl_rt_value_to_the_ddr2            (oct_ctl_rt_value_to_the_ddr2),
      .out_port_from_the_ddr2_i2c_sa           (out_port_from_the_ddr2_i2c_sa),
      .out_port_from_the_ddr2_i2c_scl          (out_port_from_the_ddr2_i2c_scl),
      .out_port_from_the_led                   (out_port_from_the_led),
      .reset_n                                 (reset_n),
      .reset_phy_clk_n_from_the_ddr2           (reset_phy_clk_n_from_the_ddr2)
    );

