% Add paths to matlab startup path
% SYNTAX:
% startup
% INPUTS:
% none
% OUTPUTS:
% none
%_______________________________________________________________________________
% Copyright (C) 2011 LIOM Laboratoire d'Imagerie Optique et Moléculaire
%                    École Polytechnique de Montréal
% Edgar Guevara
% 2012/01/30

% Result from system('dir /a:d /s /b'), except all .svn
addpath(...
    'D:\Edgar\Documents\FDOCT',...
    'D:\Edgar\Documents\FDOCT\Reconstruction 2',...
    'D:\Edgar\Documents\FDOCT\Reconstruction 2\Path_shortcuts',...
    'D:\Edgar\Documents\ssoct\Matlab\',...
    'D:\Edgar\Documents\ssoct\Matlab\Acquisition',...
    'D:\Edgar\Documents\ssoct\Matlab\IOIfast',...
    'D:\Edgar\Documents\ssoct\Matlab\Misc',...
    'D:\Edgar\Documents\ssoct\Matlab\Preprocessing',...
    'D:\Edgar\Documents\ssoct\Matlab\Processing',...
    'D:\Edgar\Documents\ssoct\Matlab\Acquisition\DATA',...
    'D:\Edgar\Documents\ssoct\Matlab\Acquisition\tcp_udp_ip',...
    'D:\Edgar\Documents\ssoct\Matlab\Acquisition\tcp_udp_ip\UDP_SIM_DAQ_DEMO',...
    'D:\Edgar\Documents\ssoct\Matlab\Misc\Calculs optiques',...
    'D:\Edgar\Documents\ssoct\Matlab\Misc\NIFTI',...
    'D:\Edgar\Documents\ssoct\Matlab\Misc\export');

% ==============================================================================
% [EOF]
