// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Wed May 18 18:11:01 2011

DE4_SOPC DE4_SOPC_inst
(
	.ext_clk(ext_clk_sig) ,	// input  ext_clk_sig
	.pll_peripheral_clk(pll_peripheral_clk_sig) ,	// output  pll_peripheral_clk_sig
	.pll_sys_clk(pll_sys_clk_sig) ,	// output  pll_sys_clk_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.in_port_to_the_ADC_data_pio(in_port_to_the_ADC_data_pio_sig) ,	// input [15:0] in_port_to_the_ADC_data_pio_sig
	.in_port_to_the_acq_busy_pio(in_port_to_the_acq_busy_pio_sig) ,	// input  in_port_to_the_acq_busy_pio_sig
	.flash_tristate_bridge_address(flash_tristate_bridge_address_sig) ,	// output [24:0] flash_tristate_bridge_address_sig
	.flash_tristate_bridge_data(flash_tristate_bridge_data_sig) ,	// inout [15:0] flash_tristate_bridge_data_sig
	.flash_tristate_bridge_readn(flash_tristate_bridge_readn_sig) ,	// output  flash_tristate_bridge_readn_sig
	.flash_tristate_bridge_writen(flash_tristate_bridge_writen_sig) ,	// output  flash_tristate_bridge_writen_sig
	.select_n_to_the_ext_flash(select_n_to_the_ext_flash_sig) ,	// output  select_n_to_the_ext_flash_sig
	.out_port_from_the_led_pio(out_port_from_the_led_pio_sig) ,	// output [7:0] out_port_from_the_led_pio_sig
	.in_port_to_the_pb_pio(in_port_to_the_pb_pio_sig) ,	// input [3:0] in_port_to_the_pb_pio_sig
	.out_port_from_the_read_RAM_address(out_port_from_the_read_RAM_address_sig) ,	// output [10:0] out_port_from_the_read_RAM_address_sig
	.out_port_from_the_seven_seg_pio(out_port_from_the_seven_seg_pio_sig) ,	// output [15:0] out_port_from_the_seven_seg_pio_sig
	.in_port_to_the_sw_pio(in_port_to_the_sw_pio_sig) ,	// input [7:0] in_port_to_the_sw_pio_sig
	.led_an_from_the_tse_mac(led_an_from_the_tse_mac_sig) ,	// output  led_an_from_the_tse_mac_sig
	.led_char_err_from_the_tse_mac(led_char_err_from_the_tse_mac_sig) ,	// output  led_char_err_from_the_tse_mac_sig
	.led_col_from_the_tse_mac(led_col_from_the_tse_mac_sig) ,	// output  led_col_from_the_tse_mac_sig
	.led_crs_from_the_tse_mac(led_crs_from_the_tse_mac_sig) ,	// output  led_crs_from_the_tse_mac_sig
	.led_disp_err_from_the_tse_mac(led_disp_err_from_the_tse_mac_sig) ,	// output  led_disp_err_from_the_tse_mac_sig
	.led_link_from_the_tse_mac(led_link_from_the_tse_mac_sig) ,	// output  led_link_from_the_tse_mac_sig
	.mdc_from_the_tse_mac(mdc_from_the_tse_mac_sig) ,	// output  mdc_from_the_tse_mac_sig
	.mdio_in_to_the_tse_mac(mdio_in_to_the_tse_mac_sig) ,	// input  mdio_in_to_the_tse_mac_sig
	.mdio_oen_from_the_tse_mac(mdio_oen_from_the_tse_mac_sig) ,	// output  mdio_oen_from_the_tse_mac_sig
	.mdio_out_from_the_tse_mac(mdio_out_from_the_tse_mac_sig) ,	// output  mdio_out_from_the_tse_mac_sig
	.ref_clk_to_the_tse_mac(ref_clk_to_the_tse_mac_sig) ,	// input  ref_clk_to_the_tse_mac_sig
	.rxp_to_the_tse_mac(rxp_to_the_tse_mac_sig) ,	// input  rxp_to_the_tse_mac_sig
	.txp_from_the_tse_mac(txp_from_the_tse_mac_sig) 	// output  txp_from_the_tse_mac_sig
);

