// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Mon Jul 04 16:32:00 2011

a2d a2d_inst
(
	.adclk(adclk_sig) ,	// input  adclk_sig
	.rdclk(rdclk_sig) ,	// input  rdclk_sig
	.cs_n(cs_n_sig) ,	// input  cs_n_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.rd(rd_sig) ,	// input  rd_sig
	.a2dc(a2dc_sig) ,	// input [11:0] a2dc_sig
	.addr(addr_sig) ,	// input [9:0] addr_sig
	.waitreq(waitreq_sig) ,	// output  waitreq_sig
	.a2do(a2do_sig) 	// output [31:0] a2do_sig
);

defparam a2d_inst.INITIAL = 'b00;
defparam a2d_inst.BUFFER0 = 'b01;
defparam a2d_inst.BUFFER1 = 'b10;
