// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Mon Jul 04 14:36:10 2011

adFIFO adFIFO_inst
(
	.data(data_sig) ,	// input [31:0] data_sig
	.rdclk(rdclk_sig) ,	// input  rdclk_sig
	.rdreq(rdreq_sig) ,	// input  rdreq_sig
	.wrclk(wrclk_sig) ,	// input  wrclk_sig
	.wrreq(wrreq_sig) ,	// input  wrreq_sig
	.q(q_sig) ,	// output [31:0] q_sig
	.rdempty(rdempty_sig) ,	// output  rdempty_sig
	.rdfull(rdfull_sig) ,	// output  rdfull_sig
	.wrfull(wrfull_sig) 	// output  wrfull_sig
);

