// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Mon Jul 04 14:36:18 2011

bufclk bufclk_inst
(
	.areset(areset_sig) ,	// input  areset_sig
	.inclk0(inclk0_sig) ,	// input  inclk0_sig
	.c0(c0_sig) ,	// output  c0_sig
	.locked(locked_sig) 	// output  locked_sig
);

