// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Tue Aug 16 14:25:02 2011

TestRead TestRead_inst
(
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.CLK48MHZ(CLK48MHZ_sig) ,	// input  CLK48MHZ_sig
	.control_go(control_go_sig) ,	// output  control_go_sig
	.control_read_base(control_read_base_sig) ,	// output [29:0] control_read_base_sig
	.control_read_length(control_read_length_sig) ,	// output [29:0] control_read_length_sig
	.control_done(control_done_sig) ,	// input  control_done_sig
	.user_buffer_data(user_buffer_data_sig) ,	// input [31:0] user_buffer_data_sig
	.user_read_buffer(user_read_buffer_sig) ,	// output  user_read_buffer_sig
	.user_data_available(user_data_available_sig) ,	// input  user_data_available_sig
	.addressLastCompleteWrite(addressLastCompleteWrite_sig) ,	// input [29:0] addressLastCompleteWrite_sig
	.addressLastCompleteRead(addressLastCompleteRead_sig) ,	// output [29:0] addressLastCompleteRead_sig
	.readingDone(readingDone_sig) ,	// output  readingDone_sig
	.debugOut(debugOut_sig) ,	// output [31:0] debugOut_sig
	.errorData(errorData_sig) 	// output [2:0] errorData_sig
);

