% Main script to start acquisition from Swept Source-Optical Coherence
% Tomography system.
% SYNTAX:
% ss_oct_acq_script
% INPUTS:
% None
% OUTPUTS:
% None
%_______________________________________________________________________________
% Copyright (C) 2011 LIOM Laboratoire d'Imagerie Optique et Moléculaire
%                    École Polytechnique de Montréal
% Edgar Guevara
% 2011/10/03

% Clear global data
clear global ssOCTdefaults
% Load default parameters
ss_oct_get_defaults

%% ------------------------- MODIFY OPTIONS ------------------------------------
global ssOCTdefaults
% dbstop if error                       % Debug (Stop if error)
ssOCTdefaults.GUI.displayLog            = false;
% Save files
ssOCTdefaults.GUI.save2file                 = true;
% Display single line/multiple lines in the interferogram plot
ssOCTdefaults.GUI.displaySingleLine     = true;
% Resample data in real-time
ssOCTdefaults.resampleData              = false;
% Correct B-scan in real time
ssOCTdefaults.GUI.corrBscan             = false;
% Show FWHM in real time
ssOCTdefaults.GUI.showFWHM              = true;
% Calculate reference from median A-line of current B-scan
ssOCTdefaults.medianRefArm              = false;
% Colormap to be used
ssOCTdefaults.GUI.OCTcolorMap           = get_colormaps('octgold');
% ------------------------------------------------------------------------------
% Read acquisition parameters generated by LabView
ssOCTdefaults.acqParam = readCSVfile(fullfile(ssOCTdefaults.folders.dirExp,...
    ssOCTdefaults.folders.acqParamFileName));

%% Establish connection to socket server running on FPGA
connect2FPGA
% Flush data buffer of the connection
flush_data

%% Start continuous acquisition
cont_acq
% ==============================================================================
% [EOF]
