% Main script to start acquisition from Swept Source-Optical Coherence
% Tomography system.
% SYNTAX:
% ss_oct_acq_script
% INPUTS:
% none
% OUTPUTS:
% none
%_______________________________________________________________________________
% Copyright (C) 2011 LIOM Laboratoire d'Imagerie Optique et Moléculaire
%                    École Polytechnique de Montréal
% Edgarmap Guevara
% 2011/10/03

% Clear global data
clear global SSOctDefaults
% Load default parameters
ss_oct_get_defaults

%% ------------------------- MODIFY OPTIONS ------------------------------------
global SSOctDefaults
SSOctDefaults.displayLog = false;
% Save files
SSOctDefaults.save2file = true;
% Read acquisition parameters generated by LabView
SSOctDefaults.acqParam = readCSVfile(fullfile(SSOctDefaults.dirExp,...
    SSOctDefaults.acqParamFileName));
% ------------------------------------------------------------------------------

%% Establish connection to socket server running on FPGA
connect2FPGA
% Flush data buffer of the connection
flush_data

%% Start continuous acquisition
cont_acq
% ==============================================================================
% [EOF]
