// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Wed May 04 12:17:25 2011

ADC_OOR ADC_OOR_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.ADC_OOR_inp(ADC_OOR_inp_sig) ,	// input  ADC_OOR_inp_sig
	.seg7D0(seg7D0_sig) ,	// output [6:0] seg7D0_sig
	.seg7D1(seg7D1_sig) 	// output [6:0] seg7D1_sig
);

